'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { formatDate, statusColor } from '@/lib/utils'
import TopBar from '@/components/layout/TopBar'
import { FileText, Plus, Loader2, ChevronDown, ChevronUp, Printer } from 'lucide-react'

const EMPTY = { client_id: '', title: '', content: '', status: 'draft' }

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([])
  const [clients, setClients] = useState<any[]>([])
  const [audits, setAudits] = useState<any[]>([])
  const [seoReports, setSeoReports] = useState<any[]>([])
  const [tasks, setTasks] = useState<any[]>([])
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState(EMPTY)
  const [saving, setSaving] = useState(false)
  const [expanded, setExpanded] = useState<string | null>(null)
  const [selectedClientId, setSelectedClientId] = useState('')
  const supabase = createClient()

  useEffect(() => { loadData() }, [])

  const loadData = async () => {
    const [{ data: r }, { data: c }, { data: a }, { data: s }, { data: t }] = await Promise.all([
      supabase.from('generated_reports').select('*,clients(name)').order('created_at', { ascending: false }),
      supabase.from('clients').select('id,name').order('name'),
      supabase.from('website_audits').select('id,url,performance_score,seo_score,created_at,client_id'),
      supabase.from('seo_reports').select('id,title,priority_actions,created_at,client_id'),
      supabase.from('tasks').select('id,title,status,priority,client_id').neq('status', 'done'),
    ])
    setReports(r ?? [])
    setClients(c ?? [])
    setAudits(a ?? [])
    setSeoReports(s ?? [])
    setTasks(t ?? [])
  }

  const set = (k: string, v: string) => setForm(f => ({ ...f, [k]: v }))

  const buildReportContent = (clientId: string) => {
    const client = clients.find(c => c.id === clientId)
    const clientAudits = audits.filter(a => a.client_id === clientId)
    const clientSeo = seoReports.filter(s => s.client_id === clientId)
    const clientTasks = tasks.filter(t => t.client_id === clientId)

    let content = `# ${client?.name ?? 'Client'} Marketing Report\n\n`
    content += `**Date:** ${new Date().toLocaleDateString('en-AU')}\n\n---\n\n`

    if (clientAudits.length) {
      content += `## Website Health\n\n`
      clientAudits.forEach(a => {
        content += `**${a.url}** — Performance: ${a.performance_score} | SEO: ${a.seo_score}\n`
      })
      content += '\n'
    }

    if (clientSeo.length) {
      content += `## SEO Summary\n\n`
      clientSeo.forEach(s => {
        content += `**${s.title}**\n${s.priority_actions ?? 'See full report.'}\n\n`
      })
    }

    if (clientTasks.length) {
      content += `## Open Tasks\n\n`
      clientTasks.forEach(t => {
        content += `- [${t.priority.toUpperCase()}] ${t.title}\n`
      })
      content += '\n'
    }

    content += `---\n*Generated by Crown Intelligence Mission Control*`
    return content
  }

  const handleGenerate = () => {
    if (!selectedClientId) return
    const content = buildReportContent(selectedClientId)
    setForm(f => ({ ...f, content, client_id: selectedClientId }))
  }

  const handleSave = async () => {
    if (!form.title) return
    setSaving(true)
    const { data: { user } } = await supabase.auth.getUser()
    await supabase.from('generated_reports').insert({ ...form, user_id: user!.id, client_id: form.client_id || null })
    setForm(EMPTY)
    setSelectedClientId('')
    setShowForm(false)
    setSaving(false)
    loadData()
  }

  return (
    <div className="flex flex-col flex-1">
      <TopBar title="Reports" subtitle={`${reports.length} total`} actions={
        <button className="btn-gold" onClick={() => setShowForm(!showForm)}>
          <Plus size={14} /> New Report
        </button>
      } />
      <div className="p-6 flex-1 space-y-4">
        {showForm && (
          <div className="ci-card max-w-2xl space-y-4">
            <h2 className="text-sm font-semibold" style={{ color: 'var(--gold-light, #E8C97A)' }}>Create Client Report</h2>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs mb-1.5" style={{ color: 'var(--text-secondary)' }}>Report Title *</label>
                <input className="ci-input" value={form.title} onChange={e => set('title', e.target.value)} placeholder="e.g. June Marketing Report" />
              </div>
              <div>
                <label className="block text-xs mb-1.5" style={{ color: 'var(--text-secondary)' }}>Status</label>
                <select className="ci-select" value={form.status} onChange={e => set('status', e.target.value)}>
                  <option value="draft">Draft</option>
                  <option value="reviewed">Reviewed</option>
                  <option value="sent">Sent</option>
                </select>
              </div>
            </div>

            <div className="p-4 rounded-lg space-y-3" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--bg-border)' }}>
              <p className="text-xs font-medium" style={{ color: 'var(--text-secondary)' }}>Auto-compile from client data</p>
              <div className="flex gap-3">
                <select className="ci-select flex-1" value={selectedClientId} onChange={e => setSelectedClientId(e.target.value)}>
                  <option value="">Select a client...</option>
                  {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                </select>
                <button className="btn-ghost flex-shrink-0" onClick={handleGenerate} disabled={!selectedClientId}>
                  Auto-fill
                </button>
              </div>
            </div>

            <div>
              <label className="block text-xs mb-1.5" style={{ color: 'var(--text-secondary)' }}>Report Content</label>
              <textarea className="ci-textarea" rows={16} value={form.content} onChange={e => set('content', e.target.value)} placeholder="Report content will appear here after auto-fill, or write manually..." style={{ fontFamily: 'monospace', fontSize: 13 }} />
            </div>
            <div className="flex gap-3">
              <button className="btn-ghost" onClick={() => setShowForm(false)}>Cancel</button>
              <button className="btn-gold" onClick={handleSave} disabled={saving || !form.title}>
                {saving ? <><Loader2 size={14} className="animate-spin" /> Saving...</> : 'Save Report'}
              </button>
            </div>
          </div>
        )}

        {!reports.length ? (
          <div className="ci-card text-center py-16">
            <FileText size={24} className="mx-auto mb-3" style={{ color: 'var(--text-muted)' }} />
            <p className="text-sm" style={{ color: 'var(--text-muted)' }}>No reports yet.</p>
          </div>
        ) : reports.map((r: any) => (
          <div key={r.id} className="ci-card">
            <div className="flex items-center justify-between cursor-pointer" onClick={() => setExpanded(expanded === r.id ? null : r.id)}>
              <div>
                <div className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>{r.title}</div>
                <div className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
                  {r.clients?.name && `${r.clients.name} · `}{formatDate(r.created_at)}
                </div>
              </div>
              <div className="flex items-center gap-2">
                <span className={`status-badge ${statusColor(r.status)}`}>{r.status}</span>
                <button className="btn-ghost text-xs px-2 py-1" onClick={(e) => { e.stopPropagation(); window.print() }}>
                  <Printer size={12} /> Print
                </button>
                {expanded === r.id ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </div>
            </div>

            {expanded === r.id && r.content && (
              <div className="mt-4" style={{ borderTop: '1px solid var(--bg-border)', paddingTop: 16 }}>
                <pre className="text-sm whitespace-pre-wrap font-sans" style={{ color: 'var(--text-secondary)' }}>{r.content}</pre>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
